name = "ASDK"
uuid = "c8c55f4a-6010-44cd-a616-9e5fc16aded6"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.1.0"

[deps]
AlpaoSDK_jll = "429efccb-d15f-50bf-9ef5-16fe0de80da4"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"

[compat]
AlpaoSDK_jll = "4.1.12"
CEnum = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
